"""Compatibility wrapper for the root AI chat manager entrypoint."""

from agent.core.ai_chat_manager import (
    ACCESS_CODE,
    AIChatManager,
    DEEPSEEK_API_BASE,
    DEEPSEEK_API_BASE_BACKUP,
    DEEPSEEK_API_KEY,
    DEEPSEEK_API_KEY_BACKUP,
    DEEPSEEK_MODEL,
    DEEPSEEK_MODEL_BACKUP,
    DEFAULT_MAX_TOKENS,
    DEFAULT_STREAM,
    DEFAULT_TEMPERATURE,
    DeepSeekStreamingChat,
    INTERNAL_TEMPLATE_URL,
    VERIFY_SSL,
    ai_chat_manager,
    get_chat_css_styles,
    streaming_data,
    streaming_lock,
)

__all__ = [
    "ACCESS_CODE",
    "AIChatManager",
    "DEEPSEEK_API_BASE",
    "DEEPSEEK_API_BASE_BACKUP",
    "DEEPSEEK_API_KEY",
    "DEEPSEEK_API_KEY_BACKUP",
    "DEEPSEEK_MODEL",
    "DEEPSEEK_MODEL_BACKUP",
    "DEFAULT_MAX_TOKENS",
    "DEFAULT_STREAM",
    "DEFAULT_TEMPERATURE",
    "DeepSeekStreamingChat",
    "INTERNAL_TEMPLATE_URL",
    "VERIFY_SSL",
    "ai_chat_manager",
    "get_chat_css_styles",
    "streaming_data",
    "streaming_lock",
]